---

- name: run kubeadm reset
  shell: "kubeadm reset"
  register: result
  failed_when: 'result.rc != 0'
  become_method: sudo
  become: True

- name: run kubeadm init master
  shell: "kubeadm init --token {{ kubeadm_token }} --api-advertise-addresses={{master_address}}"
  register: result
  failed_when: 'result.rc != 0'
  become_method: sudo
  become: True
  when: inventory_hostname in groups['master']

- debug: msg="{{ result.stdout_lines }}"
  when: inventory_hostname in groups['master']

- name: copy kube-flannel.yml 
  copy:
    src: kube-flannel.yml
    dest: "/tmp/kube-flannel.yml"
    mode: 0744
  when: inventory_hostname in groups['master']

- name: Install a pod network
  shell: "kubectl apply -f /tmp/kube-flannel.yml --validate=false"
  register: result
  failed_when: 'result.rc != 0'
  become_method: sudo
  become: True
  when: inventory_hostname in groups['master']


- name: create dashboard
  shell: "kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml"
  register: result
  failed_when: 'result.rc != 0'
  become_method: sudo
  become: True
  when: inventory_hostname in groups['master']

#- name: kubectl proxy
#  shell: "kubectl proxy"
#  register: result
#  failed_when: 'result.rc != 0'
#  become_method: sudo
#  become: True
#  when: inventory_hostname in groups['master']
  